"""Update table name to feedbacks

Revision ID: 3f52438f5c0b
Revises: e6fe8cda81a0
Create Date: 2026-09-08 18:48:38.990451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f52438f5c0b'
down_revision = 'e6fe8cda81a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('cleanliness_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('staff_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('food_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('service_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stay_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False),
    sa.Column('cleanliness_rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False),
    sa.Column('staff_rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False),
    sa.Column('food_rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False),
    sa.Column('service_rating', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedback_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('feedback_guest_id_fkey')),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], name=op.f('feedback_stay_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
