"""create department feedbacks table

Revision ID: 6ed0c31ae0c3
Revises: eae8ab2c0ec9
Create Date: 2026-09-15 11:50:13.060153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed0c31ae0c3'
down_revision = 'eae8ab2c0ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_feedbacks_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_feedbacks_feedback_id'), ['feedback_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_feedbacks_feedback_id'))
        batch_op.drop_index(batch_op.f('ix_department_feedbacks_department_id'))

    op.drop_table('department_feedbacks')
    # ### end Alembic commands ###
