"""Create feedback table

Revision ID: e6fe8cda81a0
Revises: 21e646b585a6
Create Date: 2026-09-08 18:47:34.365541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fe8cda81a0'
down_revision = '21e646b585a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('stay_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('cleanliness_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('staff_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('food_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('service_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
